name: Test

on: [push]

jobs:
  check_format:
    name: Check files are formatted with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Enable Corepack
        run: corepack enable
      - name: Enable PNPM cache
        uses: actions/setup-node@v2
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: prettier --check
        run: pnpm prettier . --check
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
  check_no_deps:
    name: Ensure no external dependency is included
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check external dependencies
        run: deno task check-deps
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Test
        run: deno test
